language: node_js
node_js:
  - 12
  - 10
  - 8
env:
  - PORT=3000
  - USERS_URL=http://www.mocky.io/v2/5808862710000087232b75ac
  - POLICIES_URL=http://www.mocky.io/v2/580891a4100000e8242b75c5

install:
  - yarn install
script:
  - yarn run test  