language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

install:
  - yarn install
script:
  - yarn run test
jobs:
  include:
    - stage: Produce Coverage
      node_js: node_js
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage