name: Backend Assessment CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: yarn install and test
      uses: Borales/actions-yarn@v2.0.0
      run: |
        yarn
        yarn run test